// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLQEjUAQN1co6FLhUqRvcniPt7SMOodkk',
    appId: '1:741301175647:web:4e189f3108297a1a59a2ea',
    messagingSenderId: '741301175647',
    projectId: 'serviup',
    authDomain: 'serviup.firebaseapp.com',
    storageBucket: 'serviup.firebasestorage.app',
    measurementId: 'G-Y8QQR67W6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjCvWx_3jiA4tIiwdSt1pNCpf5HvcvGDc',
    appId: '1:741301175647:android:0fe1a4f76554b1ab59a2ea',
    messagingSenderId: '741301175647',
    projectId: 'serviup',
    storageBucket: 'serviup.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJLxZhBIhWHZP9dBNiT6OvW5NxQdiolZs',
    appId: '1:741301175647:ios:e97977d3f8156d6b59a2ea',
    messagingSenderId: '741301175647',
    projectId: 'serviup',
    storageBucket: 'serviup.firebasestorage.app',
    androidClientId: '741301175647-4lv4rot9khu2e7t4q0kejqptbh2029r6.apps.googleusercontent.com',
    iosClientId: '741301175647-q4huu9q8dq6oq73q623qkuopqm3jcnal.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJLxZhBIhWHZP9dBNiT6OvW5NxQdiolZs',
    appId: '1:741301175647:ios:e97977d3f8156d6b59a2ea',
    messagingSenderId: '741301175647',
    projectId: 'serviup',
    storageBucket: 'serviup.firebasestorage.app',
    androidClientId: '741301175647-4lv4rot9khu2e7t4q0kejqptbh2029r6.apps.googleusercontent.com',
    iosClientId: '741301175647-q4huu9q8dq6oq73q623qkuopqm3jcnal.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLQEjUAQN1co6FLhUqRvcniPt7SMOodkk',
    appId: '1:741301175647:web:490007837ec17b8759a2ea',
    messagingSenderId: '741301175647',
    projectId: 'serviup',
    authDomain: 'serviup.firebaseapp.com',
    storageBucket: 'serviup.firebasestorage.app',
    measurementId: 'G-2KBL5GBSKJ',
  );
}
